POST http://localhost:9090/register HTTP/1.1
content-Type: application/json

{
      "name": "Yatin",
  "email": "yatin@example.com",
  "password": "123456",
  "username": "yatin12"
}

###

POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
  "email": "piyush@example.com",
  "password": "123456"
}

###

GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
  "token":"95fcbb620e6d280d9f7804eac839524e56ea90d4cb71fa7a83eff7a5144c5b29"
}

###

GET http://localhost:9090/user/get_all_users
Content-Type: application/json


###
POST http://localhost:9090/update_profile_data
Content-type:application/json

{
  "token":"cde5fed078ce86196df27e440f881da7dd38ec182904273ae75b5a9a34aa6887",
  "bio":"Hey I am Yatin, I am from Delhi, I work in XYZ Company",
  "currentPostion":"CTO",
  "pastWork":[
    {
      "company":"Microsoft",
      "position":"CTO",
      "years":"2+"
    }
  ],
  "education":[
    {
      "school":"IIIT",
      "degree":"B.Tech",
      "fieldOfStudy":"2015-2019"
    }
  ]
}